### ISSUE TITLE
won't work if default parameter is array with multiple items

### ISSUE THREAD

**Issue by leonardiwagner** [renolc/get-function-params#1]
doesn't work with `function someFunc(x = [1, 2, 3])`

>SyntaxError: Unexpected token )
    at decode (index.js:32:19)
    at module.exports.encode.split.filter.map (index.js:49:34)
    at Array.map (native)
    at module.exports (index.js:44:6)

though it works with `function someFunc(x = [])` or `function someFunc(x = [1])`, and even `function someFunc(x = {a: 1, b: 2, c: 3})`

**Comment by renolc** [comment]
Thanks for the issue. Sorry for the delayed response:  for some reason I had this repo unwatched. >.<

Yeah, I've been meaning to revamp this module somewhat. It's a little inconsistent right now. The failing scenario is much appreciated. I'll be sure to add it to my suite when I upgrade. :)

**Comment by renolc** [comment]
This should be fixed in 2.0.1
